apiVersion: apps/v1
kind: Deployment
metadata:
  name: akeyless-python-app
  namespace: akeyless-k8s-python-demo

spec:
  replicas: 1
  # Keep only 1 old replicaSet in history to keep the list clean
  revisionHistoryLimit: 1
  
  selector:
    matchLabels:
      app: akeyless-python-app

  template:
    metadata:
      labels:
        app: akeyless-python-app

    spec:
      serviceAccountName: akeyless-python-sa

      containers:
      - name: python-app
        image: leonmaister/akeyless-k8s-python-demo:5.1
        imagePullPolicy: Always