apiVersion: batch/v1
kind: Job
metadata:
  name: akeyless-retrieval-job
  namespace: akeyless-kubernetes-authentication-demo
spec:
  template:
    spec:
      serviceAccountName: akeyless-kubernetes-authentication-sa
      containers:
      - name: python-app
        image: leonmaister/akeyless-kubernetes-authentication-demo:5.1
        imagePullPolicy: Always
      restartPolicy: Never 
  backoffLimit: 2 